apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: jenkins-home

spec:

  accessModes:

    - ReadWriteOnce

  resources:

    requests:

      storage: 69Gi

---

apiVersion: v1

kind: Pod

metadata:

  name: jenkins

  labels: 

    app: jenkins

spec:

  securityContext:

    fsGroup: 1000

  containers:

    - name: jenkins

      securityContext:

        runAsUser: 1000

      image: jenkins/jenkins:lts-alpine

      ports:

      - containerPort: 8080

      volumeMounts:

        - mountPath: "/var/jenkins_home"

          name: jenkins-home

  volumes:

    - name: jenkins-home

      persistentVolumeClaim:

        claimName: jenkins-home

---

apiVersion: v1

kind: Service

metadata:

  name: jenkins

spec:

  selector:

    app: jenkins

  ports:

  - protocol: TCP

    port: 80

    targetPort: 8080

  type: LoadBalancer
