- hosts: swarm
  become: true
  tasks:
  - name: python-pip install
    apt:
      name: python-pip
      state: present
      update_cache: true
  - name: install docker sdk
    pip:
      name: docker
  - name: Clone dockerpj
    git:
      repo: 'https://github.com/LeeroyC710/dockerpj'
      dest: /home/jenkins/dockerpj         
  - name: docker-swarm-init
    docker_swarm:
      state: present
  - name: building images
    docker_compose:
      project_src: /home/jenkins/dockerpj
      build: true
  - name: docker-compose down
    shell: | 
      cd/home/jenkins/dockerpj/
      docker-compose down
    remote_user: jenkins
  - name: Deploy the stack
    docker_stack:
      state: present
      name: dockerpj
      compose:
      - /home/jenkins/dockerpj/docker-compose.yaml
